name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build API Docker image
        run: |
          docker build -t theosementa0/demo-nestjs-api-vehicle ./backend
          
      - name: Build frontend Docker image
        run: |
          docker build -t theosementa0/demo-react-frontend ./frontend

      - name: Push API Docker image
        run: |
          docker push theosementa0/demo-nestjs-api-vehicle:latest

      - name: Push frontend Docker image
        run: |
          docker push theosementa0/demo-react-frontend:latest

      - name: Notify Discord about new Docker image
        run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
            "content": "🎉 New Docker image pushed! The backend and frontend images for the NestJS API and React application are now available on Docker Hub. 🚀",
            "username": "Docker CI Bot",
            "avatar_url": "https://example.com/your-avatar.png"
          }'
